import Head from 'next/head'
import SelectData from '../components/SelectData'
import ListOfMovies from '../components/ListOfMovies'

export default function Home() {
  return (
    <>
      <Head>
        <title>Relevent Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" bg-slate-700">
        <h1 className="text-white font-semibold text-[25px]">You like One there are others similar :) </h1>
          <div className="w-[100%]">
              <div className="m-auto w-[70%] p-[10px]">
                  <h1 className="text-white font-semibold ">Choose a movie you Love</h1>
                  <SelectData/>
                  <ListOfMovies />
                </div>
          </div>
      </div>
    </>
  )
}
